spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/doggie_walks
    username: doggie_user
    password: doggie_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Esto hace que si cambias tu clase Java, la BD se actualice sola (magia)
    show-sql: true      # Para ver las consultas en la consola
    properties:
      hibernate:
        format_sql: true # Para ver el SQL bonito
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080